### ISSUE TITLE
Add EDEN to installed simulators on OSB docker

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/neuralensemble-docker#12]
FYI @spanag have a look at my branches here for the latest with updated versions:
https://github.com/NeuralEnsemble/neuralensemble-docker/network

**Comment by spanag** [comment]
I just implemented a binary wheel and uploaded it on PyPI ( https://pypi.org/project/eden-simulator/ ), which should allow installation with one line for most users. Should EDEN be installed here through pip, or from source (for a more customised build)?

**Comment by pgleeson** [comment]
Thanks @spanag. I tried pip installing it inside an ubuntu docker container and it worked fine. A few things:
- It failed to install on Mac with pip, not sure how it should build etc. on Mac (any idea @sanjayankur31)? Issue here: https://gitlab.com/neurocomputing-lab/Inferior_OliveEMC/eden/-/issues/2
- The pip package is called eden-simulator and you need to `import eden-simulator` not eden_tools (so docs need updating), even though it's tools in here: https://gitlab.com/neurocomputing-lab/Inferior_OliveEMC/eden/-/tree/main/testing/python_package/eden_tools

**Comment by spanag** [comment]
It is compiled code, wheels have to be rebuilt for each OS/arch target.
I don't have Mac experience, but the system calls (basically `dlopen`) seem compatible. With some GNU tooling, it just might work as it is.

> The pip package is called eden-simulator and you need to import eden-simulator not eden_tools

That's right, I considered having `eden_tools` be a wrapper around locally built EDEN, vs. `eden_simulator` that's bundled with its own copy. Because giving the same name might be even worse headache to users...

**Comment by spanag** [comment]
It is compiled code, wheels have to be rebuilt for each OS/arch target.
I don't have Mac experience, but the OS calls (basically dlopen) look compatible. With some GNU tooling, it just might work as it is.

> The pip package is called eden-simulator and you need to import eden-simulator not eden_tools

I considered having eden_tools be a wrapper around locally built EDEN, vs. eden_simulator that's bundled with its own copy. Because giving the same name might be even worse headache to users...

**Comment by spanag** [comment]
At long last, the python package issue is resolved (with "hollow wheels" for local builds) and the dependency on pynml is removed, so Eden can be installed straight from `pip`.

Above commits also changes `git clone git://github.com/NeuralEnsemble/neuroConstruct.git` to use https instead, I'm not sure if it's the same but `docker build` didn't like the former.
