### ISSUE TITLE
Tagged images with released versions of PyNN

### ISSUE THREAD

**Issue by pgleeson** [NeuralEnsemble/neuralensemble-docker#7]
The [latest and py2 images](https://hub.docker.com/r/neuralensemble/simulation/tags/) from Docker Hub are updated when files in this repo are modified. These have recently changed from PyNN 0.8.2 to PyNN 0.9.0.

It would be good to be able to point to (base a new Dockerfile on) a fixed/stable release of these images with the versions of the simulators that are all compliant with the release of PyNN at the time.

Can I suggest making tags in the simulation/simulationx images:

py3_pynn090
py2_pynn090
py3_pynn091
py2_pynn091
etc.

I think this can be achieved with just making a tag in this GH repo and setting the Build settings in Dockerhub to build on new tags.

The latest and py2 images can still point to the latest version in the master/python 2 branches.

**Comment by apdavison** [comment]
I've tagged the current latest and py2 images.

**Comment by apdavison** [comment]
The problem with building on tags is that, at present, only the “base" image build is triggered by a push and so only that one would be tagged. “simulation" is then triggered by the rebuild of the “base” image and “simulationx” by the rebuild of “simulation”. Since all three Dockerfiles are in the same repository, this is the only way I found to ensure the builds are all consistent (happen in the right order). Docker Hub seems to expect that each Dockerfile will be in a separate Git repo.

**Comment by pgleeson** [comment]
@apdavison thanks. I've used the tagged version in [my docker file](https://github.com/OpenSourceBrain/neuralensemble-docker/commit/5339ee766e5e0d73a5018a8ae1a7b32f883782aa#diff-818a5713cd4fe3318b96b40fee99d4d3R9) which will solve the immediate issue with changing images.
